version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: fsc-events-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fsc-events
    volumes:
      - fsc-events-postgres-data:/var/lib/postgresql/data

volumes:
  fsc-events-postgres-data:
